version: "3.9"

services:
    nginx:
        build: nginx
        ports:
          - 80:8080
          - 443:8443
        depends_on:
          - api

    api:
        build: smart-word-hints-api
        environment:
          - PORT=8081
        ports:
          - 8081:8081
