# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-27 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_of_speech', models.CharField(choices=[('v', 'verb'), ('n', 'noun'), ('adv', 'adverb'), ('adj', 'adjective'), ('pron', 'pronoun'), ('prep', 'preposition'), ('conj', 'conjunction'), ('inter', 'interjection')], max_length=5)),
                ('meaning', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('en', 'English'), ('pl', 'Polish')], max_length=2)),
                ('word', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='translation',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.Word'),
        ),
    ]
