FROM nginx

COPY nginx.conf /etc/nginx/nginx.conf
COPY /etc/letsencrypt/live/api.domain.com/fullchain.pem /etc/letsencrypt/live/api.domain.com/fullchain.pem
COPY /etc/letsencrypt/live/api.domain.com/fullchain.pem /etc/letsencrypt/live/api.domain.com/privkey.pem